deployment:
  tasks:
    - export DEPLOYPATH=/home/sunnyco2/public_html
    - /bin/chmod -R 755 $DEPLOYPATH/web/sites/default
    - /bin/rsync -a --exclude='.git' --exclude='web/sites/default/files' --delete ./ $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    - cd $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer audit
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - vendor/bin/drush cr
    - vendor/bin/drush updb -y
