_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 525d00c5-32e7-4c39-98ea-ff41140bb379
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /adventure-blog
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
