#!/bin/bash

## Make the backup
# ssh ssh://sunnyco2@sunnyco2.mi3-cl9-its5.a2hosting.com:7822 
# cd public_html
# rm -rf db
# mkdir db
# vendor/bin/drush sql:dump --result-file=~/public_html/db/tmp.sql -vvv

## Import Locally
rm db/latest.sql
scp -P 7822 sunnyco2@sunnyco2.mi3-cl9-its5.a2hosting.com:/home/sunnyco2/public_html/db/tmp.sql db/latest.sql
sed -i '1d' db/latest.sql
fin db import db/latest.sql