#!/bin/bash

echo "Attempting to generate settings files."

rm ./web/sites/default/settings.local.php
cp ./web/sites/default/default.settings.local.php ./web/sites/default/settings.local.php

fin drush site-install minimal --config-dir=../config --existing-config --account-name="admin" --account-pass="admin" -y

fin drush cim -y
